# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A simple statistical function generator using Rcpp.
#' @description A simple statistical function generator using Rcpp.
#' @return a density fucntion \code{y1}.
#' @return a distribution fucntion \code{y2}.
#' @return a quantile fucntion \code{y3}.
#' @examples
#' \dontrun{
#' f18()
#' }
#' @export
f18 <- function() {
    .Call('_StatComp22072_f18', PACKAGE = 'StatComp22072')
}

